### ISSUE TITLE
DUNE_QUERY_ID clarifications

### ISSUE THREAD

**Issue by rolandgvc** [bh2smith/duneapi#55]
Great work on this library! I have a question about `DUNE_QUERY_ID`. What is its need if we are already passing `raw_sql`? Alternatively, shouldn't we be able to pass the query id without the SQL code, just like in https://github.com/itzmestar/duneanalytics?

**Comment by bh2smith** [comment]
Hey there. great questions you have asked here and glad you like this library! 

1.  Why is `DUNE_QUERY_ID` needed if we are already passing `raw_sql`?

you may notice that there currently is not any method to "create" a Dune query and recover the ID of the created query from this library. I also tend to avoid implementation of this, because then one could programmatically create infinite numbers of queries on Dune servers (something I would respectfully like to avoid giving people the ability to do). 

2. Shouldn't we be able to pass QUERY_ID without the `raw_sql`? 

YES absolutely, this was a lack of foresight during the original implementation. My initial purposes did not quite fit this description since my original use was to "update, execute and fetch" so I was always updating the query first. Of course one may simply want to execute and fetch the results for an existing query. I would very much like to implement this (I belive there is already a todo in the code), but this change would also be a breakign change in the current library API. Specifically `DuneAPI.execute` takes an object of type `DuneQuery`, when it should really take an `int` (query id). I have been considering the possibility of creating a second method `execute`(I suppose the word for this is method override) which would not require a major version bump. 

Overall, I would like to do this, but need to find the time....

**Comment by rolandgvc** [comment]
Awesome tip, thanks!
